#!/bin/sh
#
# Modified version of FreeBSD 11.3 nfsd startup script that
# starts nfsd in the background waiting for the local-filesystems
# lock
#

# PROVIDE: nfsd
# REQUIRE: mountd hostname gssd nfsuserd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfsd"
desc="Remote NFS server"
rcvar="nfs_server_enable"
command="/usr/sbin/${name}"

load_rc_config $name
start_precmd="nfsd_precmd"
sig_stop="USR1"

nfsd_precmd()
{
	rc_flags="${nfs_server_flags}"

	# Load the modules now, so that the vfs.nfsd sysctl
	# oids are available.
	load_kld nfsd

	if checkyesno nfs_reserved_port_only; then
		echo 'NFS on reserved port only=YES'
		sysctl vfs.nfsd.nfs_privport=1 > /dev/null
	else
		sysctl vfs.nfsd.nfs_privport=0 > /dev/null
	fi

	if checkyesno nfsv4_server_enable || \
	    checkyesno nfs_server_managegids; then
		force_depend nfsuserd || err 1 "Cannot run nfsuserd"
	fi

	if checkyesno nfsv4_server_enable; then
		sysctl vfs.nfsd.server_max_nfsvers=4 > /dev/null
	else
		echo 'NFSv4 is disabled'
		sysctl vfs.nfsd.server_max_nfsvers=3 > /dev/null
	fi

	force_depend rpcbind || return 1
	force_depend mountd || return 1
}

waitfor() {
  FIRST=yes
  while [ ! -f "/var/run/$1.done" ]; do
      if [ $FIRST = yes ]; then
	  echo "${name}: Waiting for '$1' to finish..."
	  FIRST=no
      fi
      sleep 1
  done
}

case "$1" in
    faststart)
	(waitfor "mountd" ; run_rc_command "$1") &
	;;
    *)
	run_rc_command "$1"
	;;
esac

